addSbtPlugin("com.lucidchart"   % "sbt-scalafmt"         % "1.14")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.3.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.3.2")
addSbtPlugin("io.get-coursier"  % "sbt-coursier"         % "1.0.0-RC13")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "0.2.1")
